openapi: 3.0.3
info:
  title: restream
  description: ''
  license:
    name: ''
  version: 0.1.0
paths: {}
components:
  schemas:
    JwtToken:
        allOf:
          - type: object
            required:
              - sub
              - exp
            properties:
              sub: 
                type: string
              exp:
                type: integer
                format: int64
                minimum: 0
          - $ref: '#/components/schemas/ModulesClaims'
    LimitByKey:
      type: object
      required:
        - limit
        - key
      properties:
        key:
          type: string
        limit:
          type: integer
          format: int64
          minimum: 0
    ModulesClaims:
      type: object
      properties:
        conn_limits:
          type: array
          items:
            $ref: '#/components/schemas/LimitByKey'
        publish:
          $ref: '#/components/schemas/PubPermissions'
        rpc:
          $ref: '#/components/schemas/RpcPermissions'
        subscribe:
          $ref: '#/components/schemas/SubPermissions'
    PubPermission:
      type: object
      required:
        - topic
      properties:
        topic:
          $ref: '#/components/schemas/TopicPermission'
    PubPermissions:
      type: object
      required:
        - topics
      properties:
        topics:
          type: array
          items:
            $ref: '#/components/schemas/PubPermission'
    RpcPermission:
      type: object
      required:
        - topic
      properties:
        topic:
          $ref: '#/components/schemas/TopicPermission'
    RpcPermissions:
      type: object
      required:
        - topics
      properties:
        topics:
          type: array
          items:
            $ref: '#/components/schemas/RpcPermission'
    SubPermission:
      type: object
      required:
        - topic
      properties:
        topic:
          $ref: '#/components/schemas/TopicPermission'
    SubPermissions:
      type: object
      required:
        - topics
        - subs_limits
      properties:
        subs_limits:
          type: array
          items:
            $ref: '#/components/schemas/LimitByKey'
        topics:
          type: array
          items:
            $ref: '#/components/schemas/SubPermission'
    TopicPermission:
      type: string


