/* tslint:disable */
/* eslint-disable */
/**
 * restream
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LimitByKey
 */
export interface LimitByKey {
    /**
     * 
     * @type {string}
     * @memberof LimitByKey
     */
    key: string;
    /**
     * 
     * @type {number}
     * @memberof LimitByKey
     */
    limit: number;
}

/**
 * Check if a given object implements the LimitByKey interface.
 */
export function instanceOfLimitByKey(value: object): value is LimitByKey {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function LimitByKeyFromJSON(json: any): LimitByKey {
    return LimitByKeyFromJSONTyped(json, false);
}

export function LimitByKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LimitByKey {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'limit': json['limit'],
    };
}

export function LimitByKeyToJSON(value?: LimitByKey | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'limit': value['limit'],
    };
}

