/* tslint:disable */
/* eslint-disable */
/**
 * restream
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const MqttProperties = {
    SubId: "sub_id",
    Offset: "offset",
    Recoverable: "recoverable",
    Status: "status",
    ErrorReason: "error_reason",
} as const;
export type MqttProperties =
    (typeof MqttProperties)[keyof typeof MqttProperties];

export function instanceOfMqttProperties(value: any): boolean {
    for (const key in MqttProperties) {
        if (Object.prototype.hasOwnProperty.call(MqttProperties, key)) {
            if (
                (MqttProperties as Record<string, MqttProperties>)[key] ===
                value
            ) {
                return true;
            }
        }
    }
    return false;
}

export function MqttPropertiesFromJSON(json: any): MqttProperties {
    return MqttPropertiesFromJSONTyped(json, false);
}

export function MqttPropertiesFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): MqttProperties {
    return json as MqttProperties;
}

export function MqttPropertiesToJSON(value?: MqttProperties | null): any {
    return value as any;
}
