/* tslint:disable */
/* eslint-disable */
/**
 * restream
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PubPermission
 */
export interface PubPermission {
    /**
     * 
     * @type {string}
     * @memberof PubPermission
     */
    topic: string;
}

/**
 * Check if a given object implements the PubPermission interface.
 */
export function instanceOfPubPermission(value: object): value is PubPermission {
    if (!('topic' in value) || value['topic'] === undefined) return false;
    return true;
}

export function PubPermissionFromJSON(json: any): PubPermission {
    return PubPermissionFromJSONTyped(json, false);
}

export function PubPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PubPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'topic': json['topic'],
    };
}

export function PubPermissionToJSON(value?: PubPermission | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'topic': value['topic'],
    };
}

