/* tslint:disable */
/* eslint-disable */
/**
 * restream
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PubPermission } from './PubPermission';
import {
    PubPermissionFromJSON,
    PubPermissionFromJSONTyped,
    PubPermissionToJSON,
} from './PubPermission';

/**
 * 
 * @export
 * @interface PubPermissions
 */
export interface PubPermissions {
    /**
     * 
     * @type {Array<PubPermission>}
     * @memberof PubPermissions
     */
    topics: Array<PubPermission>;
}

/**
 * Check if a given object implements the PubPermissions interface.
 */
export function instanceOfPubPermissions(value: object): value is PubPermissions {
    if (!('topics' in value) || value['topics'] === undefined) return false;
    return true;
}

export function PubPermissionsFromJSON(json: any): PubPermissions {
    return PubPermissionsFromJSONTyped(json, false);
}

export function PubPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PubPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'topics': ((json['topics'] as Array<any>).map(PubPermissionFromJSON)),
    };
}

export function PubPermissionsToJSON(value?: PubPermissions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'topics': ((value['topics'] as Array<any>).map(PubPermissionToJSON)),
    };
}

