/* tslint:disable */
/* eslint-disable */
/**
 * restream
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcPermission } from './RpcPermission';
import {
    RpcPermissionFromJSON,
    RpcPermissionFromJSONTyped,
    RpcPermissionToJSON,
} from './RpcPermission';

/**
 * 
 * @export
 * @interface RpcPermissions
 */
export interface RpcPermissions {
    /**
     * 
     * @type {Array<RpcPermission>}
     * @memberof RpcPermissions
     */
    topics: Array<RpcPermission>;
}

/**
 * Check if a given object implements the RpcPermissions interface.
 */
export function instanceOfRpcPermissions(value: object): value is RpcPermissions {
    if (!('topics' in value) || value['topics'] === undefined) return false;
    return true;
}

export function RpcPermissionsFromJSON(json: any): RpcPermissions {
    return RpcPermissionsFromJSONTyped(json, false);
}

export function RpcPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'topics': ((json['topics'] as Array<any>).map(RpcPermissionFromJSON)),
    };
}

export function RpcPermissionsToJSON(value?: RpcPermissions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'topics': ((value['topics'] as Array<any>).map(RpcPermissionToJSON)),
    };
}

