/* tslint:disable */
/* eslint-disable */
/**
 * restream
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcPermission
 */
export interface RpcPermission {
    /**
     * 
     * @type {string}
     * @memberof RpcPermission
     */
    topic: string;
}

/**
 * Check if a given object implements the RpcPermission interface.
 */
export function instanceOfRpcPermission(value: object): value is RpcPermission {
    if (!('topic' in value) || value['topic'] === undefined) return false;
    return true;
}

export function RpcPermissionFromJSON(json: any): RpcPermission {
    return RpcPermissionFromJSONTyped(json, false);
}

export function RpcPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'topic': json['topic'],
    };
}

export function RpcPermissionToJSON(value?: RpcPermission | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'topic': value['topic'],
    };
}

